/*
 * This file was automatically generated by EvoSuite
 * Tue Jan 07 07:29:24 GMT 2025
 */

package com.thealgorithms.datastructures.crdt;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.thealgorithms.datastructures.crdt.Bias;
import com.thealgorithms.datastructures.crdt.Element;
import com.thealgorithms.datastructures.crdt.LWWElementSet;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, resetStaticState = true) 
public class LWWElementSet_ESTest_0 extends LWWElementSet_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      LWWElementSet lWWElementSet0 = new LWWElementSet();
      // Undeclared exception!
      try { 
        lWWElementSet0.remove((Element) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.thealgorithms.datastructures.crdt.LWWElementSet", e);
      }
  }
}
