/*
 * This file was automatically generated by EvoSuite
 * Tue Jan 07 07:29:00 GMT 2025
 */

package com.thealgorithms.sorts;

import org.junit.Test;
import static org.junit.Assert.*;
import com.thealgorithms.sorts.BucketSort;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, resetStaticState = true) 
public class BucketSort_ESTest_0 extends BucketSort_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      BucketSort bucketSort0 = new BucketSort();
  }
}
