/*
 * This file was automatically generated by EvoSuite
 * Tue Jan 07 10:22:48 GMT 2025
 */

package com.thealgorithms.datastructures.trees;

import org.junit.Test;
import static org.junit.Assert.*;
import com.thealgorithms.datastructures.trees.BSTRecursiveGeneric;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, resetStaticState = true) 
public class BSTRecursiveGeneric_ESTest_1 extends BSTRecursiveGeneric_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      String[] stringArray0 = new String[2];
      BSTRecursiveGeneric.main(stringArray0);
      assertEquals(2, stringArray0.length);
  }
}
