/*
 * This file was automatically generated by EvoSuite
 * Tue Jan 07 07:30:39 GMT 2025
 */

package com.thealgorithms.maths;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.thealgorithms.maths.SecondMinMax;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, resetStaticState = true) 
public class SecondMinMax_ESTest_0 extends SecondMinMax_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      int[] intArray0 = new int[2];
      // Undeclared exception!
      try { 
        SecondMinMax.findSecondMax(intArray0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Input array should have at least 2 distinct elements
         //
         verifyException("com.thealgorithms.maths.SecondMinMax", e);
      }
  }
}
