/*
 * This file was automatically generated by EvoSuite
 * Tue Jan 07 10:30:25 GMT 2025
 */

package com.thealgorithms.searches;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.thealgorithms.searches.BinarySearch;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, resetStaticState = true) 
public class BinarySearch_ESTest_2 extends BinarySearch_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      BinarySearch binarySearch0 = new BinarySearch();
      assertNotNull(binarySearch0);
      
      Integer[] integerArray0 = new Integer[9];
      Integer integer0 = new Integer(2023);
      assertEquals(2023, (int)integer0);
      assertNotNull(integer0);
      
      integerArray0[0] = integer0;
      integerArray0[1] = integer0;
      integerArray0[4] = integerArray0[1];
      int int0 = binarySearch0.find(integerArray0, integerArray0[0]);
      assertEquals(9, integerArray0.length);
      assertEquals(4, int0);
  }
}
