/*
 * This file was automatically generated by EvoSuite
 * Tue Jan 07 10:30:25 GMT 2025
 */

package com.thealgorithms.searches;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.thealgorithms.searches.BinarySearch;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, resetStaticState = true) 
public class BinarySearch_ESTest_4 extends BinarySearch_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      BinarySearch binarySearch0 = new BinarySearch();
      assertNotNull(binarySearch0);
      
      Integer integer0 = new Integer((-2602));
      assertEquals((-2602), (int)integer0);
      assertNotNull(integer0);
      
      // Undeclared exception!
      try { 
        binarySearch0.find((Integer[]) null, integer0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.thealgorithms.searches.BinarySearch", e);
      }
  }
}
