/*
 * This file was automatically generated by EvoSuite
 * Tue Jan 07 10:30:25 GMT 2025
 */

package com.thealgorithms.searches;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.thealgorithms.searches.BinarySearch;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, resetStaticState = true) 
public class BinarySearch_ESTest_0 extends BinarySearch_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      BinarySearch binarySearch0 = new BinarySearch();
      assertNotNull(binarySearch0);
      
      Integer[] integerArray0 = new Integer[1];
      Integer integer0 = new Integer(19);
      assertEquals(19, (int)integer0);
      assertNotNull(integer0);
      
      integerArray0[0] = integer0;
      Integer integer1 = new Integer(1811);
      assertEquals(1811, (int)integer1);
      assertNotNull(integer1);
      assertFalse(integer1.equals((Object)integer0));
      
      int int0 = binarySearch0.find(integerArray0, integer1);
      assertEquals(1, integerArray0.length);
      assertEquals((-1), int0);
      assertFalse(integer1.equals((Object)integer0));
  }
}
