/*
 * This file was automatically generated by EvoSuite
 * Tue Jan 07 10:23:12 GMT 2025
 */

package com.thealgorithms.searches;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.thealgorithms.searches.LowerBound;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, resetStaticState = true) 
public class LowerBound_ESTest_3 extends LowerBound_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      LowerBound lowerBound0 = new LowerBound();
      assertNotNull(lowerBound0);
      
      Integer[] integerArray0 = new Integer[4];
      Integer integer0 = new Integer(1);
      assertEquals(1, (int)integer0);
      assertNotNull(integer0);
      
      integerArray0[0] = integer0;
      integerArray0[1] = integer0;
      integerArray0[2] = integerArray0[0];
      int int0 = lowerBound0.find(integerArray0, integerArray0[2]);
      assertEquals(1, int0);
      assertEquals(4, integerArray0.length);
  }
}
