/*
 * This file was automatically generated by EvoSuite
 * Tue Jan 07 10:23:12 GMT 2025
 */

package com.thealgorithms.searches;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.thealgorithms.searches.LowerBound;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, resetStaticState = true) 
public class LowerBound_ESTest_0 extends LowerBound_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      LowerBound lowerBound0 = new LowerBound();
      assertNotNull(lowerBound0);
      
      Integer[] integerArray0 = new Integer[6];
      Integer integer0 = new Integer((-3391));
      assertEquals((-3391), (int)integer0);
      assertNotNull(integer0);
      
      integerArray0[2] = integer0;
      Integer integer1 = new Integer(7);
      assertEquals(7, (int)integer1);
      assertNotNull(integer1);
      assertFalse(integer1.equals((Object)integer0));
      
      integerArray0[4] = integer1;
      Integer integer2 = new Integer((-2025));
      assertEquals((-2025), (int)integer2);
      assertNotNull(integer2);
      assertFalse(integer2.equals((Object)integer1));
      assertFalse(integer2.equals((Object)integer0));
      
      // Undeclared exception!
      try { 
        lowerBound0.find(integerArray0, integer2);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }
}
