/*
 * This file was automatically generated by EvoSuite
 * Tue Jan 07 12:08:45 GMT 2025
 */

package com.thealgorithms.datastructures.trees;

import org.junit.Test;
import static org.junit.Assert.*;
import com.thealgorithms.datastructures.trees.BSTRecursiveGeneric;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, resetStaticState = true) 
public class BSTRecursiveGeneric_ESTest_0 extends BSTRecursiveGeneric_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      BSTRecursiveGeneric<Integer> bSTRecursiveGeneric0 = new BSTRecursiveGeneric<Integer>();
      assertNotNull(bSTRecursiveGeneric0);
      
      boolean boolean0 = bSTRecursiveGeneric0.find((Integer) null);
      assertFalse(boolean0);
  }
}
