/*
 * This file was automatically generated by EvoSuite
 * Tue Jan 07 07:31:04 GMT 2025
 */

package com.thealgorithms.maths;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.thealgorithms.maths.SecondMinMax;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, resetStaticState = true) 
public class SecondMinMax_ESTest_5 extends SecondMinMax_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      // Undeclared exception!
      try { 
        SecondMinMax.findSecondMin((int[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.thealgorithms.maths.SecondMinMax", e);
      }
  }
}
