/*
 * This file was automatically generated by EvoSuite
 * Tue Jan 07 07:31:04 GMT 2025
 */

package com.thealgorithms.maths;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.thealgorithms.maths.SecondMinMax;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, resetStaticState = true) 
public class SecondMinMax_ESTest_1 extends SecondMinMax_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      int[] intArray0 = new int[2];
      intArray0[0] = (-783);
      int int0 = SecondMinMax.findSecondMin(intArray0);
      assertEquals(0, int0);
  }
}
