/*
 * This file was automatically generated by EvoSuite
 * Tue Jan 07 10:21:34 GMT 2025
 */

package com.thealgorithms.sorts;

import org.junit.Test;
import static org.junit.Assert.*;
import com.thealgorithms.sorts.IntrospectiveSort;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, resetStaticState = true) 
public class IntrospectiveSort_ESTest_0 extends IntrospectiveSort_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      IntrospectiveSort introspectiveSort0 = new IntrospectiveSort();
      assertNotNull(introspectiveSort0);
  }
}
